version: '3'
services:
        mica:
                image: obiba/mica:latest
                ports:
                        - "8445:8445"
                        - "8082:8082"
                links:
                        - mongo
                environment:
                        - JAVA_OPTS=-Xmx2G
                        - MICA_ADMINISTRATOR_PASSWORD=${MICA_ADMINISTRATOR_PASSWORD}
                        - MICA_ANONYMOUS_PASSWORD=password
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - AGATE_HOST=agate
                        - AGATE_PORT=8444
                volumes:
                        - /home/syncuser/projects/synchros/mica_home:/srv
        mongo:
                image: mongo:4.2
        agate:
                image: obiba/agate:latest
                ports:
                        - "8444:8444"
                        - "8081:8081"
                links:
                        - mongo
                environment:
                        - AGATE_ADMINISTRATOR_PASSWORD=${AGATE_ADMINISTRATOR_PASSWORD}
                        - MONGO_HOST=mongo
                        - MONGO_PORT=27017
                        - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY}
                        - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY}
                volumes:
                        - /home/syncuser/projects/synchros/agate_home:/srv
